"""
PDF generation utility for NexusCode agents.

Converts markdown content to professional PDF documents using weasyprint.
Stores PDFs in the generated_documents table (PostgreSQL BYTEA).
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from typing import Any

from src.utils.logging import get_secure_logger

logger = get_secure_logger(__name__)

# ── Severity badge colours ─────────────────────────────────────────────────────

_SEVERITY_COLOURS: dict[str, str] = {
    "critical": "#c0392b",
    "high":     "#e67e22",
    "medium":   "#f39c12",
    "low":      "#27ae60",
    "info":     "#2980b9",
}

_DEFAULT_SEVERITY_COLOUR = "#7f8c8d"


def _severity_colour(severity: str | None) -> str:
    if not severity:
        return _DEFAULT_SEVERITY_COLOUR
    return _SEVERITY_COLOURS.get(severity.lower(), _DEFAULT_SEVERITY_COLOUR)


# ── Table of contents generation ──────────────────────────────────────────────

def _build_toc(content: str) -> str:
    """Build a simple HTML table of contents from ## headers."""
    toc_entries = []
    for line in content.splitlines():
        m = re.match(r"^(#{1,3})\s+(.+)$", line)
        if m:
            level = len(m.group(1))
            title = m.group(2).strip()
            anchor = re.sub(r"[^a-z0-9-]", "", title.lower().replace(" ", "-"))
            indent = (level - 1) * 16
            toc_entries.append(
                f'<li style="margin-left:{indent}px"><a href="#{anchor}">{title}</a></li>'
            )

    if not toc_entries:
        return ""

    return (
        '<div class="toc">'
        "<h2>Contents</h2>"
        "<ul>" + "".join(toc_entries) + "</ul>"
        "</div>"
    )


def _add_header_anchors(html: str) -> str:
    """Add id anchors to h1/h2/h3 tags for TOC links."""
    def _replace(m: re.Match) -> str:
        tag = m.group(1)
        attrs = m.group(2) or ""
        text = re.sub(r"<[^>]+>", "", m.group(3))
        anchor = re.sub(r"[^a-z0-9-]", "", text.lower().replace(" ", "-"))
        return f"<{tag}{attrs} id=\"{anchor}\">{m.group(3)}</{tag}>"

    return re.sub(r"<(h[1-3])([^>]*)>(.*?)</h[1-3]>", _replace, html, flags=re.DOTALL)


# ── CSS template ──────────────────────────────────────────────────────────────

_CSS = """
@page {
    margin: 2cm;
    @bottom-center {
        content: "Generated by NexusCode on %(datetime)s  ·  Page " counter(page) " of " counter(pages);
        font-family: 'DejaVu Sans', Arial, sans-serif;
        font-size: 9pt;
        color: #7f8c8d;
    }
}

body {
    font-family: 'DejaVu Sans', Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #2c3e50;
    background: #ffffff;
}

.header {
    border-bottom: 3px solid #2c3e50;
    padding-bottom: 12px;
    margin-bottom: 24px;
}

.header-brand {
    font-size: 9pt;
    font-weight: bold;
    color: #7f8c8d;
    text-transform: uppercase;
    letter-spacing: 2px;
}

.header-title {
    font-size: 20pt;
    font-weight: bold;
    color: #1a1a2e;
    margin: 6px 0 8px 0;
    line-height: 1.2;
}

.severity-badge {
    display: inline-block;
    padding: 3px 10px;
    border-radius: 4px;
    font-size: 9pt;
    font-weight: bold;
    color: #ffffff;
    text-transform: uppercase;
    letter-spacing: 1px;
    background-color: %(severity_colour)s;
}

.toc {
    background: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 6px;
    padding: 16px 20px;
    margin-bottom: 24px;
    page-break-inside: avoid;
}

.toc h2 {
    font-size: 11pt;
    color: #495057;
    margin: 0 0 10px 0;
    text-transform: uppercase;
    letter-spacing: 1px;
}

.toc ul {
    list-style: none;
    margin: 0;
    padding: 0;
}

.toc li {
    padding: 2px 0;
}

.toc a {
    color: #2980b9;
    text-decoration: none;
    font-size: 10pt;
}

h1 {
    font-size: 16pt;
    font-weight: bold;
    color: #1a1a2e;
    border-bottom: 2px solid #dee2e6;
    padding-bottom: 6px;
    margin-top: 24px;
    page-break-after: avoid;
}

h2 {
    font-size: 13pt;
    font-weight: bold;
    color: #2c3e50;
    margin-top: 20px;
    page-break-after: avoid;
}

h3 {
    font-size: 11pt;
    font-weight: bold;
    color: #34495e;
    margin-top: 16px;
    page-break-after: avoid;
}

p {
    margin: 8px 0;
    orphans: 3;
    widows: 3;
}

code {
    font-family: 'DejaVu Sans Mono', 'Courier New', monospace;
    font-size: 9pt;
    background: #f4f4f4;
    padding: 2px 5px;
    border-radius: 3px;
    color: #c0392b;
}

pre {
    font-family: 'DejaVu Sans Mono', 'Courier New', monospace;
    font-size: 9pt;
    background: #f8f9fa;
    border-left: 4px solid #6c757d;
    padding: 12px 16px;
    overflow-wrap: break-word;
    white-space: pre-wrap;
    border-radius: 0 4px 4px 0;
    margin: 12px 0;
    page-break-inside: avoid;
}

pre code {
    background: transparent;
    padding: 0;
    color: #2c3e50;
    border-radius: 0;
}

table {
    width: 100%%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 10pt;
    page-break-inside: avoid;
}

thead tr {
    background: #2c3e50;
    color: #ffffff;
}

th {
    padding: 8px 12px;
    text-align: left;
    font-weight: bold;
}

td {
    padding: 7px 12px;
    border-bottom: 1px solid #dee2e6;
}

tbody tr:nth-child(even) {
    background: #f8f9fa;
}

blockquote {
    border-left: 4px solid #3498db;
    margin: 12px 0;
    padding: 8px 16px;
    background: #ebf5fb;
    color: #21618c;
    border-radius: 0 4px 4px 0;
}

ul, ol {
    margin: 8px 0;
    padding-left: 24px;
}

li {
    margin: 4px 0;
}

strong {
    color: #2c3e50;
}

.meta-table {
    width: 100%%;
    margin-bottom: 16px;
}

.meta-table td {
    padding: 4px 8px;
    font-size: 10pt;
    border: none;
}

.meta-table td:first-child {
    font-weight: bold;
    color: #7f8c8d;
    width: 140px;
}

hr {
    border: none;
    border-top: 1px solid #dee2e6;
    margin: 20px 0;
}
"""


def _build_html(
    content_html: str,
    title: str,
    metadata: dict[str, Any],
    toc_html: str,
    now_str: str,
) -> str:
    """Wrap rendered content in a full HTML document with NexusCode styling."""
    severity = metadata.get("severity", "")
    sev_colour = _severity_colour(severity)
    badge_html = (
        f'<span class="severity-badge">{severity.upper()}</span>'
        if severity
        else ""
    )

    # Build metadata table rows
    meta_rows = ""
    meta_display = {
        k: v for k, v in metadata.items()
        if k not in ("severity",) and v
    }
    if meta_display:
        rows = "".join(
            f"<tr><td>{k.replace('_', ' ').title()}</td><td>{v}</td></tr>"
            for k, v in meta_display.items()
        )
        meta_rows = f'<table class="meta-table">{rows}</table>'

    css = _CSS % {"datetime": now_str, "severity_colour": sev_colour}

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>{css}</style>
</head>
<body>
<div class="header">
    <div class="header-brand">NexusCode</div>
    <div class="header-title">{title}</div>
    {badge_html}
</div>
{meta_rows}
{toc_html}
{content_html}
</body>
</html>"""


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_pdf_from_markdown(
    content: str,
    title: str,
    metadata: dict[str, Any] | None = None,
) -> bytes:
    """
    Convert markdown content to PDF bytes.

    Args:
        content:  Full markdown document text.
        title:    Document title shown in the PDF header.
        metadata: Optional key-value pairs (service, severity, environment, author, etc.).

    Returns:
        Raw PDF bytes.
    """
    import markdown as _markdown  # type: ignore[import-untyped]
    import weasyprint

    if metadata is None:
        metadata = {}

    now_str = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    # Convert markdown → HTML
    content_html = _markdown.markdown(
        content,
        extensions=["tables", "fenced_code", "codehilite", "nl2br", "sane_lists"],
    )

    # Add anchor IDs to headers so TOC links work
    content_html = _add_header_anchors(content_html)

    # Build table of contents from the original markdown (before HTML conversion)
    toc_html = _build_toc(content)

    full_html = _build_html(
        content_html=content_html,
        title=title,
        metadata=metadata,
        toc_html=toc_html,
        now_str=now_str,
    )

    pdf_bytes: bytes = weasyprint.HTML(string=full_html).write_pdf()
    return pdf_bytes


async def store_document(
    pdf_bytes: bytes,
    title: str,
    filename: str,
    run_id: str | None = None,
    step_id: str | None = None,
    metadata: dict[str, Any] | None = None,
) -> str:
    """
    Insert a generated PDF into the generated_documents table.

    Returns:
        doc_id (UUID string) of the newly created row.
    """
    from sqlalchemy import text

    from src.storage.db import AsyncSessionLocal

    if metadata is None:
        metadata = {}

    import json

    async with AsyncSessionLocal() as session:
        row = (
            await session.execute(
                text("""
                    INSERT INTO generated_documents
                        (run_id, step_id, title, filename, pdf_bytes, size_bytes, metadata)
                    VALUES
                        (:run_id, :step_id, :title, :filename, :pdf_bytes, :size_bytes, CAST(:metadata AS jsonb))
                    RETURNING id
                """),
                {
                    "run_id": run_id,
                    "step_id": step_id,
                    "title": title,
                    "filename": filename,
                    "pdf_bytes": pdf_bytes,
                    "size_bytes": len(pdf_bytes),
                    "metadata": json.dumps(metadata),
                },
            )
        ).mappings().first()
        await session.commit()

    doc_id: str = row["id"]
    logger.info(
        "pdf_generator: stored document doc_id=%s title=%r size=%d run_id=%s",
        doc_id, title, len(pdf_bytes), run_id,
    )
    return doc_id


async def get_documents_for_step(
    run_id: str,
    step_id: str,
) -> list[dict]:
    """
    Return all generated_documents for a specific run+step.

    Used by the workflow executor to attach document metadata to step output.
    """
    from sqlalchemy import text

    from src.storage.db import AsyncSessionLocal

    async with AsyncSessionLocal() as session:
        rows = (
            await session.execute(
                text("""
                    SELECT id, filename, size_bytes, title, created_at
                    FROM generated_documents
                    WHERE run_id = :run_id AND step_id = :step_id
                    ORDER BY created_at
                """),
                {"run_id": run_id, "step_id": step_id},
            )
        ).mappings().all()

    return [dict(r) for r in rows]


def slugify(text: str) -> str:
    """Convert a title to a safe filename slug."""
    slug = text.lower()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"\s+", "-", slug.strip())
    slug = re.sub(r"-{2,}", "-", slug)
    return slug[:80]
